### PR TITLE
unit(s) #176

### PR DESCRIPTION
**Pull request by SamStudio8**
good enough 

closes #177

### CODE REVIEW

**Comment by zuzak** [comment]
closes #177

**Comment by SamStudio8** [comment]
i did it

**Comment by SamStudio8** [comment]
surprise tests have appeared

**Comment by zuzak** [comment]
The `!abv` command is plural almost all of the time.
I think the only time it'll actually neatly hit `1` is when you ask for the ABV of a shot of whisky.
It seems disproportionate to add `(s)` after every result?

**Pull request closed without merging**
